Resources:
  MyVPC2:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.8.0/21"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: "MyVPCfromCF"
subnetName:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "ap-northeast-1a"
      VpcId: !Ref MyVPC2
      CidrBlock: "10.0.8.0/24"
      Tags:
        - Key: Name
          Value: "subnet1formCE"